---
name: WWW-Scroogle
version: 0.0132_001
author:
  - Lars Hartmann
abstract: Perl Extension for Scroogle
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  LWP: 5.808
  perl: 5.6.1
  strict: 0
  warnings: 0
build_requires:
  Test::More: 0
provides:
  WWW::Scroogle:
    file: lib/WWW/Scroogle.pm
    version: 0.0132_001
  WWW::Scroogle::Result:
    file: lib/WWW/Scroogle/Result.pm
    version: 0.003
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
